###
GET http://localhost:8080/api/v1/credentials
Accept: application/json

###
GET http://localhost:8080/api/v1/credentials/6ba85fd3-74ba-4df8-968c-cd75c7aa78b4
Accept: application/json

###
GET http://localhost:8080/api/v1/credentials/6ba85fd3-74ba-4df8-968c-cd75c7aa78b4/archive
Accept: application/json

###
POST http://localhost:8080/api/v1/credentials
Content-Type: application/json

{
  "url": "www.tam.tu",
  "email": "email",
  "password": "pass"
}

###
POST http://localhost:8080/api/v1/credentials
Content-Type: application/json

{
  "id": "b5c7adfc-bc91-4e94-ab41-4400493d98e4",
  "url": "www.tam.tu",
  "email": "email",
  "password": "pass"
}